version: "3.8"
services:
  webapache:
    container_name: servapache
    build:
      context: ./../
      dockerfile: ./prueba1/Dockerfile
      # dockerfile: ./prueba1/Dockerfile.httpd
    ports:
      - "8080:80"
    volumes:
      - ../web:/var/www/html